/* Automatically generated by chibi-ffi; version: 0.2 */

#include <chibi/eval.h>

#include <X11/Xlib.h>

#include <stdlib.h>

static sexp sexp_system_stub (sexp ctx, sexp self, sexp_sint_t n, sexp arg0) {
  sexp res;
  if (! sexp_stringp(arg0))
    return sexp_type_exception(ctx, self, SEXP_STRING, arg0);
  res = sexp_make_integer(ctx, system(sexp_string_data(arg0)));
  return res;
}

static sexp sexp_XOpenDisplay_stub (sexp ctx, sexp self, sexp_sint_t n, sexp arg0) {
  Display *tmp;
  sexp res;
  if (! (sexp_stringp(arg0) || sexp_not(arg0)))
    return sexp_type_exception(ctx, self, SEXP_STRING, arg0);
  res = sexp_make_cpointer(ctx, sexp_unbox_fixnum(sexp_opcode_return_type(self)), XOpenDisplay(sexp_string_maybe_null_data(arg0)), SEXP_FALSE, 0);
  return res;
}

static sexp sexp_XCloseDisplay_stub (sexp ctx, sexp self, sexp_sint_t n, sexp x) {
  if (sexp_cpointer_freep(x))
    XCloseDisplay(sexp_cpointer_value(x));
  return SEXP_VOID;
}


sexp sexp_init_library (sexp ctx, sexp self, sexp_sint_t n, sexp env, const char* version, sexp_abi_identifier_t abi) {
  sexp sexp_Display_type_tag;
  sexp_gc_var3(name, tmp, op);
  if (!(sexp_version_compatible(ctx, version, sexp_version)
        && sexp_abi_compatible(ctx, abi, SEXP_ABI_IDENTIFIER)))
    return sexp_global(ctx, SEXP_G_ABI_ERROR);
  sexp_gc_preserve3(ctx, name, tmp, op);
  name = sexp_c_string(ctx, "Display", -1);
  sexp_Display_type_tag = sexp_register_c_type(ctx, name, sexp_XCloseDisplay_stub);
  tmp = sexp_make_type_predicate(ctx, name, sexp_Display_type_tag);
  name = sexp_intern(ctx, "Display?", 8);
  sexp_env_define(ctx, env, name, tmp);
  op = sexp_define_foreign(ctx, env, "system", 1, (sexp_proc1)sexp_system_stub);
  if (sexp_opcodep(op)) {
    sexp_opcode_return_type(op) = sexp_make_fixnum(SEXP_FIXNUM);
    sexp_opcode_arg1_type(op) = sexp_make_fixnum(SEXP_STRING);
  }
  op = sexp_define_foreign(ctx, env, "XOpenDisplay", 1, (sexp_proc1)sexp_XOpenDisplay_stub);
  if (sexp_opcodep(op)) {
    sexp_opcode_return_type(op) = sexp_make_fixnum(sexp_type_tag(sexp_Display_type_tag));
    sexp_opcode_arg1_type(op) = sexp_make_fixnum(SEXP_STRING);
  }
  sexp_gc_release3(ctx);
  return SEXP_VOID;
}

